---
title: "new-class-enrollment"
author: "Shojeh Liu"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googlesheets4)
library(fs)
library(readxl)
library(tidyverse)
library(janitor)
```

```{r download_data, include=FALSE}
url_current <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"


url_old <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx"

download.file(url_current,
              destfile = "current.xlsx")
              
download.file(url_old,
              destfile = "old.xlsx")

```

```{r}
old <- read_excel("class_enrollment_summary_by_term_2.25.20_0 (1).xlsx", skip = 3) %>%
  clean_names() 

current <- read_excel("class_enrollment_summary_by_term_3.22.19_0.xlsx", skip=3) %>%
  clean_names()

combined <- anti_join(current, old, by = "course_id") %>%
  arrange(desc(total)) %>%
  slice(1:5) %>%
  print()

combined
```

